// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IFeatherBookOpen: typeof import('~icons/feather/book-open')['default']
    IFeatherDownload: typeof import('~icons/feather/download')['default']
    IFeatherFileText: typeof import('~icons/feather/file-text')['default']
    IFeatherHome: typeof import('~icons/feather/home')['default']
    IFeatherInfo: typeof import('~icons/feather/info')['default']
    IVscodeIconsDefaultFolder: typeof import('~icons/vscode-icons/default-folder')['default']
    NA: typeof import('naive-ui')['NA']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NH1: typeof import('naive-ui')['NH1']
    NH2: typeof import('naive-ui')['NH2']
    NIcon: typeof import('naive-ui')['NIcon']
    NIconWrapper: typeof import('naive-ui')['NIconWrapper']
    NInput: typeof import('naive-ui')['NInput']
    NLi: typeof import('naive-ui')['NLi']
    NP: typeof import('naive-ui')['NP']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTree: typeof import('naive-ui')['NTree']
    NUl: typeof import('naive-ui')['NUl']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
