name: Build and deploy to pages

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js LTS
        uses: actions/setup-node@v3.3.0
        with:
          node-version: "*"
      - name: Install dependencies
        run: yarn
      - name: Build project
        run: yarn build
      - name: Build redbean executable
        uses: TimonLukas/action-static-redbean@v0.2.6
      - run: mv redbean.com dist/server.com
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: dist
